---
version: "1.3.3"
slug: "node_server"
name: "EnOcean Binding"
description: "Starts a node.js webserver, exposing a Web API to control EnOcean WRLs"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "services"
boot: "auto"
uart: true

ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "Webservice API"

options:
  adapter:
schema:
  adapter: "str"
