---
version: '1.3.3'
slug: 'node_server'
name: 'EnOcean Binding'
description: 'Starts a Bun webserver, exposing a Web API to control EnOcean WRLs'
init: false
arch:
  - aarch64
  - amd64
startup: 'services'
boot: 'auto'
uart: true
services:
  - mqtt:need

ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: 'Webservice API'

options:
  transport_type: 'none'
  transport_path: ''
  baud_rate: 57600
  rtscts: false
schema:
  transport_type: 'list(none|serial|tcp)'
  transport_path: 'str'
  baud_rate: 'int'
  rtscts: 'bool'
