/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacketListenerRouteImport } from './routes/packet-listener'
import { Route as PairingRouteImport } from './routes/pairing'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsHomeassistantRouteImport } from './routes/settings.homeassistant'
import { Route as SettingsMqttRouteImport } from './routes/settings.mqtt'
import { Route as SettingsTransportRouteImport } from './routes/settings.transport'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacketListenerRoute = PacketListenerRouteImport.update({
  id: '/packet-listener',
  path: '/packet-listener',
  getParentRoute: () => rootRouteImport,
} as any)
const PairingRoute = PairingRouteImport.update({
  id: '/pairing',
  path: '/pairing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHomeassistantRoute = SettingsHomeassistantRouteImport.update({
  id: '/settings/homeassistant',
  path: '/settings/homeassistant',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMqttRoute = SettingsMqttRouteImport.update({
  id: '/settings/mqtt',
  path: '/settings/mqtt',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTransportRoute = SettingsTransportRouteImport.update({
  id: '/settings/transport',
  path: '/settings/transport',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/packet-listener': typeof PacketListenerRoute
  '/pairing': typeof PairingRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/homeassistant': typeof SettingsHomeassistantRoute
  '/settings/mqtt': typeof SettingsMqttRoute
  '/settings/transport': typeof SettingsTransportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/packet-listener': typeof PacketListenerRoute
  '/pairing': typeof PairingRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/homeassistant': typeof SettingsHomeassistantRoute
  '/settings/mqtt': typeof SettingsMqttRoute
  '/settings/transport': typeof SettingsTransportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/packet-listener': typeof PacketListenerRoute
  '/pairing': typeof PairingRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/homeassistant': typeof SettingsHomeassistantRoute
  '/settings/mqtt': typeof SettingsMqttRoute
  '/settings/transport': typeof SettingsTransportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/packet-listener'
    | '/pairing'
    | '/settings/general'
    | '/settings/homeassistant'
    | '/settings/mqtt'
    | '/settings/transport'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/packet-listener'
    | '/pairing'
    | '/settings/general'
    | '/settings/homeassistant'
    | '/settings/mqtt'
    | '/settings/transport'
  id:
    | '__root__'
    | '/'
    | '/packet-listener'
    | '/pairing'
    | '/settings/general'
    | '/settings/homeassistant'
    | '/settings/mqtt'
    | '/settings/transport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PacketListenerRoute: typeof PacketListenerRoute
  PairingRoute: typeof PairingRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsHomeassistantRoute: typeof SettingsHomeassistantRoute
  SettingsMqttRoute: typeof SettingsMqttRoute
  SettingsTransportRoute: typeof SettingsTransportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packet-listener': {
      id: '/packet-listener'
      path: '/packet-listener'
      fullPath: '/packet-listener'
      preLoaderRoute: typeof PacketListenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairing': {
      id: '/pairing'
      path: '/pairing'
      fullPath: '/pairing'
      preLoaderRoute: typeof PairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/homeassistant': {
      id: '/settings/homeassistant'
      path: '/settings/homeassistant'
      fullPath: '/settings/homeassistant'
      preLoaderRoute: typeof SettingsHomeassistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/mqtt': {
      id: '/settings/mqtt'
      path: '/settings/mqtt'
      fullPath: '/settings/mqtt'
      preLoaderRoute: typeof SettingsMqttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/transport': {
      id: '/settings/transport'
      path: '/settings/transport'
      fullPath: '/settings/transport'
      preLoaderRoute: typeof SettingsTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PacketListenerRoute: PacketListenerRoute,
  PairingRoute: PairingRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsHomeassistantRoute: SettingsHomeassistantRoute,
  SettingsMqttRoute: SettingsMqttRoute,
  SettingsTransportRoute: SettingsTransportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
